package api

const (
	API_URL_A                        = "http://localhost:20180"
	API_URL_B                        = "http://localhost:20190"
	ROUTE_NEW_PROGRAMME              = "v1/programme/new"
	ROUTE_LOAD_PROGRAMME             = "v1/programme/load"
	ROUTE_LOAD_PROGRAMME_BLUE_TEAM   = "v1/programme/load/blue/team"
	ROUTE_MOVE_PROGRAMME             = "v1/programme/move"
	ROUTE_QUICK_MOVE_PROGRAMME       = "v1/programme/quick/move"
	ROUTE_SCAN_PROGRAMME             = "v1/programme/scan"
	ROUTE_GET_CELLULE_LOG            = "v1/programme/cellule/log"
	ROUTE_CLEAN_CELLULE_LOG          = "v1/programme/clean/cellule/log"
	ROUTE_EXPLORE_PROGRAMME          = "v1/programme/explore"
	ROUTE_DESTROY_PROGRAMME          = "v1/programme/destroy"
	ROUTE_REBUILD_PROGRAMME          = "v1/programme/rebuild"
	ROUTE_STATUS_GRID                = "v1/grid"
	ROUTE_STATUS_PROGRAMME           = "v1/programme/infos"
	ROUTE_CAPTURE_CELL_DATA          = "v1/programme/capture/cellule/data"
	ROUTE_CAPTURE_CELL_ENERGY        = "v1/programme/capture/cellule/energy"
	ROUTE_CAPTURE_TARGET_DATA        = "v1/programme/capture/target/data"
	ROUTE_CAPTURE_TARGET_ENERGY      = "v1/programme/capture/target/energy"
	ROUTE_EQUILIBRiUM                = "v1/programme/equilibrium"
	ROUTE_PUSH_FLAG                  = "v1/programme/push/flag"
	ROUTE_DESTROY_ZONE               = "v1/programme/destroy/zone"
	ROUTE_NAVIGATION_PROGRAMME_STOP  = "v1/programme/navigation/stop"
	ROUTE_EXPLORATION_PROGRAMME_STOP = "v1/programme/exploration/stop"
	ROUTE_STOP_MOVE_PROGRAMME        = "v1/programme/stop/move"
	ROUTE_ESTIMATE_MOVE_PROGRAMME    = "v1/programme/estimate/move"
	ROUTE_ZONE_SHELLCODE             = "v1/zone/shellcode/:id/:secretid"
	ROUTE_ACTIVE_SHELLCODE           = "v1/active/shellcode/:id/:secretid/:target_id/:shellcode"
)
